FROM hacdias/filemanager


EXPOSE 80
# CMD ["filemanager", "--port", "80", "-s", "/volumes"]

# docker build -t local/files -f Dockerfile.files .
# docker run -it --rm -p 8081:80 --name files local/files
