#!/bin/sh

# Permissions
chown -R $USER_NAME:$USER_NAME ${HOME}/.eclipse
chown -R $USER_NAME:$USER_NAME ${ECLIPSE_WORKSPACE}
chown -R $USER_NAME:$USER_NAME ${HOME}/git
chown -R $USER_NAME:$USER_NAME ${HOME}/.m2
chown -R $USER_NAME:$USER_NAME ${HOME}/scratch

# Run
su - $USER_NAME

touch ${HOME}/.gitconfig
if [ -f ${HOME}/git/.gitconfig ] ; then
  cp -f ${HOME}/git/.gitconfig ${HOME}/.gitconfig
fi

/opt/eclipse/eclipse
